routes/admin.php
<?php
Route::resource('/posts', 'PostController');
Route::get('/', function () {

    return view('auth.login');

})->middleware('guest');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/', 'HomeController@index');
Route::post('/user-block/{id}', 'HomeController@userBlockActions')->name('block-actions');
Route::resource('comments', 'CommentController')->only([
    'destroy', 'store'
]);
Route::get('/login/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('/login/callback/{provider}', 'Auth\LoginController@handleProviderCallback');

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $fillable = [
        'user_id', 'post_id', 'text',
    ];

    protected $dates = [
        'created_at',
    ];

    protected $with = ['user','post'];


    public function user(){
        return $this->hasOne(User::class,'id','user_id');
    }

    public function post(){
        return $this->hasOne(Post::class,'id','post_id');
    }
}

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = [
        'title', 'body', 'stage',
    ];


    public function comments()
    {
        return $this->hasMany(Comment::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','is_admin','is_active'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Post;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\PostRequest;
use Illuminate\Support\Str;

class PostController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('can:isAdmin');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index(Request $request)
    {
        $posts = Post::orderBy('id','desc')->paginate(20);
        return view('admin.posts.index', compact('posts'));
    }

    public function create()
    {
        return view('admin.posts.create');
    }

    public function edit($id)
    {
        $post = Post::findOrFail($id);
        return view('admin.posts.edit', compact('post'));
    }

    public function destroy($id)
    {
        Post::destroy($id);
        flash('Successfully deleted post');
        return redirect()->back();

    }

    public function update(PostRequest $request,$id)
    {
        $post = Post::findOrFail($id);
        $post->update($request->all());
        flash('Successfully updated post');

        return redirect()->route('posts.index');
    }

    public function store(PostRequest $request)
    {

        Post::create($request->all());
        flash('Successfully created new post');

        return redirect()->route('posts.index');

    }
}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use App\Comment;
use App\Post;
use Illuminate\Http\Request;
use App\Http\Requests\CommentRequest;
use Illuminate\Support\Facades\Auth;

class CommentController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware(['auth','can:isActive']);
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function store(CommentRequest $request)
    {

        $post = Post::whereId($request->post_id)->first();

        if(!$post){
            return response()->json(['errors'=>['post'=>['Post not found']]],421);
        }

        $request->request->add(['user_id'=>Auth::id()]);
        Comment::create($request->all());
        return response()->json(['postId'=>$request->post_id],200);
    }

    public function destroy($id)
    {
        $this->middleware('can:isAdmin');

        Comment::destroy($id);
        return redirect()->back();
    }

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use App\User;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */


    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index(Request $request)
    {
        $posts = Post::where('stage', 'production')->with(['comments' => function ($q) {
            return $q->orderBy('created_at', 'desc');
        }])->orderBy('created_at', 'desc')->paginate(5);


        return view('home', compact('posts'));
    }

    public function userBlockActions($id)
    {
        $this->middleware('can:isAdmin');


        $user = User::findOrFail($id);

        if ($user->is_active === 1) {
            $user->update(['is_active' => 0]);
        } else {
            $user->update(['is_active' => 1]);
        }

        return redirect()->back();

    }

}

resources/views/admin/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
     <style>
         .invalid-feedback{
             display: block;
         }
     </style>
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
        <div class="container">
            <a class="navbar-brand" href="/" style="color: #FF2D20;border: 1px solid #FF2D20;padding: 5px;border-radius: 10px">
                Admin Dashboard
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->

                @auth
                    <ul class="navbar-nav mr-auto">
                        <li  class="nav-item @if(request()->is('*/posts*')) active @endif"><a class="nav-link" href="{{route('posts.index')}}">Posts</a></li>
                    </ul>
                @endauth


                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        <li class="nav-item">
                            <a class="nav-link" href="/admin">{{ __('Login') }}</a>
                        </li>
                    @else
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>

    <main class="py-4">
        <div class="row justify-content-center">
            <div class="col-md-8">
                @include('flash::message')
            </div>
        </div>
        @yield('content')
    </main>
</div>
</body>
</html>

resources/views/admin/posts/create.blade.php
@extends('admin.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header"> NEW POST</div>

                    <div class="card-body">
                        <div class="row p-2" >
                            <a href="{{route('posts.index')}}" class="btn btn-primary ml-auto" >Back </a>
                        </div>
                        <form method="POST" action="{{route('posts.store')}}">
                            @csrf
                            @include('admin.posts.form')
                            <div class="form-group row mb-0">
                                <div class="col-md-8 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        Submit
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/posts/edit.blade.php
@extends('admin.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Edit post <strong>{{$post->title}}</strong></div>

                    <div class="card-body">
                        <div class="row p-2" >
                            <a href="{{route('posts.index')}}" class="btn btn-primary ml-auto" >Back </a>
                        </div>
                        <form method="POST" action="{{route('posts.update',$post->id)}}">
                            @csrf
                            <input type="hidden" name="_method" value="PUT">
                            @include('admin.posts.form')
                            <div class="form-group row mb-0">
                                <div class="col-md-8 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        Submit
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/posts/form.blade.php
<div class="form-group row">
    <label class="col-md-4 col-form-label text-md-right" for="title">Title</label>
    <div class="col-md-6">
        <input type="text" class="form-control  @error('title') is-invalid @enderror" name="title" id="title" value="{{$post->title ?? old('title')}}">
        @error('title')
        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
        @enderror
    </div>
</div>

<div class="form-group row">
    <label class="col-md-4 col-form-label text-md-right" for="stage">Stage</label>
    <div class="col-md-6">
        <select class="form-control  @error('stage') is-invalid @enderror" name="stage" id="stage">
            <option selected disabled>Select one</option>
            <option value="moderation" @if(isset($post) && $post->stage==='moderation') selected @endif>Moderation</option>
            <option value="production" @if(isset($post) && $post->stage==='production') selected @endif>Production</option>
        </select>
        @error('stage')
        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
        @enderror
    </div>
</div>

<div class="form-group row">
    <label class="col-md-4 col-form-label text-md-right" for="body">Body</label>
    <div class="col-md-6">
        <textarea class="form-control  @error('body') is-invalid @enderror" id="body" name="body">@if(isset($post) ){{$post->body}}@else{{old('body')}}@endif</textarea>
        @error('body')
        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
        @enderror
    </div>
</div>

resources/views/admin/posts/index.blade.php
@extends('admin.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">Posts</div>

                    <div class="card-body">
                        <div class="row p-2" >
                            <a href="{{route('posts.create')}}" class="btn btn-primary  ml-auto" style="float: right!important;">Add </a>
                        </div>

                        <div class="row p-2">
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                    <tr>
                                        <th>ID</th>
                                        <th>TITLE</th>
                                        <th>STAGE</th>
                                        <th>ACTIONS</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($posts as $post)
                                        <tr>
                                            <td>{{$post->id}}</td>
                                            <td>{{$post->title}}</td>
                                            <td>{{$post->stage}}</td>
                                            <td>
                                                <div class="btn-group">
                                                    <a style="margin-right: 4px"
                                                       href="{{ route('posts.edit', $post->id) }}"
                                                       title="Edit Post">
                                                        <button class="btn btn-success">Edit
                                                        </button>
                                                    </a>

                                                    <form method="POST"
                                                          action="{{ route('posts.destroy',  $post->id) }}"
                                                          accept-charset="UTF-8" style="display:inline">
                                                        {{ method_field('DELETE') }}
                                                        {{ csrf_field() }}
                                                        <button type="submit" class="btn btn-danger"
                                                                title="Delete Post"
                                                                onclick="return confirm(&quot;Confirm delete?&quot;)">Del
                                                        </button>
                                                    </form>
                                                </div>

                                            </td>
                                        </tr>
                                    @endforeach



                                    </tbody>
                                </table>
                                {{$posts->links()}}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')
@section('style')
    <style>


    </style>
@endsection

@section('content')
    <div class="container">
        <div class="row justify-content-center">

            @auth
                @cannot('isActive')
                    <div class="col-md-8">
                        <div class="alert alert-danger alert-dismissible">
                            <strong>Attention!</strong> You are blocked by admin,You can read only.
                        </div>
                    </div>
                @endcannot
            @endauth

            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">
                        <h2 class="text-center">Blogs</h2>
                    </div>

                    <div class="card-body">
                        <div class="infinite-scroll" style="">
                            @foreach($posts as $post)
                                @include('includes.post')
                            @endforeach
                            {{ $posts->links() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        @include('modals.comment-modal')
        @include('modals.warning-modal')
    </div>
@endsection
@section('script')

    <script type="text/javascript">
        $('ul.pagination').hide();
        $(function () {
            $('.infinite-scroll').jscroll({
                autoTrigger: true,
                debug: true,
                loadingHtml: '<div class="spinner-border text-primary" style="font-size: 30px;"></div>',
                padding: 0,
                nextSelector: '.pagination li.active + li a',
                contentSelector: 'div.infinite-scroll',
                callback: function () {
                    $('ul.pagination').remove();
                }
            });
        });

        function shareTwitter(id,title) {
            {
                window.open("https://twitter.com/share?url=" + escape(window.location.href + '/#article' + id) + "&text=" + title, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');
                return false;
            }
        }

        @if(Auth::check())
        @can('isActive')


        function openCommentModal(postId, postTitle) {

            $('#post_id').val(postId);
            $('.title').text(postTitle);
            $('#commentModal').modal()
        }


        $('#commentModal').on('hide.bs.modal', function () {
            $('#post_id').val(null);
            $('#text').val(null);
            $('.title').text(null);
        });

        $('#commentStore').submit(function (e) {
            e.preventDefault();
            $.ajax({
                headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                type: 'POST',
                url: '{{route('comments.store')}}',
                data: $(this).serialize(),
                success: function (data) {
                    // window.location.href = '/#article'+data.postId
                    window.location.reload()
                },
                error: function (error) {
                    var resp = error.responseJSON.errors;
                    Object.keys(resp).forEach(function (i) {
                        $('#error').text(resp[i][0])
                    });
                }
            });
        })

        @endcan

        @endif


    </script>
@endsection

resources/views/includes/comment.blade.php
<dl>
    <dt>
        @if(Auth::check() && $comment->user->id === Auth::id()) <strong
            style="color: #1d68a7">You</strong> @else  {{$comment->user->name}}  @endif

        @can('isAdmin')


            @if(Auth::id() !== $comment->user->id)
                <form method="POST"
                      action="{{route('block-actions',$comment->user->id)}}"
                      accept-charset="UTF-8" style="display:inline">
                    @csrf
                    <button type="submit" class="btn"
                            title="@if($comment->user->is_active === 1) Block @else Unlock @endif {{$comment->user->name}}"
                            onclick="return confirm(&quot;Confirm action?&quot;)"><i
                            class="fa @if($comment->user->is_active === 1) fa-lock @else fa-unlock @endif"
                            aria-hidden="true" style="float: right"></i>
                    </button>
                </form>
            @endif
            <form method="POST"
                  action="{{route('comments.destroy',$comment->id)}}"
                  accept-charset="UTF-8" style="display:inline;float: right">
                {{ method_field('DELETE') }}
                @csrf
                <button type="submit" class="btn" style="color: darkred"
                        title="Delete Comment"
                        onclick="return confirm(&quot;Confirm delete?&quot;)"><i class="fa fa-remove "
                                                                                 style="float: right"></i>
                </button>
            </form>
        @endcan


    </dt>
    <dd class="text-right" style="color: red"></dd>
    <dd style="color: grey">  {{$comment->text}}</dd>
    <dd style="color: black;text-align: right;font-size: 12px">
        {{ \Carbon\Carbon::parse($comment->created_at)->diffForHumans() }}
    </dd>
</dl>
<hr>

resources/views/includes/post.blade.php
<article class="article p-3 mb-2"
         style="border: 1px solid grey;border-radius: 5px;box-shadow: 0 0 5px grey;"
         id="article{{$post->id}}">
    <h3 class="text-center">{{$post->title}}</h3>
    <hr>
    <p class="p-2">{{$post->body}}</p>
    <div class="row p-2" style="">
        <div class="btn-group ml-auto">


            <button type="button" class="btn btn-round btn-primary mr-1"
                    onclick='shareTwitter("{{$post->id}}","{{$post->title}}")'
                    title="Share on Twitter"><i class="fa fa-twitter"></i></button>

            <button type="button" class="btn btn-round btn-primary mr-1"
                    data-toggle="collapse" data-target="#comments{{$post->id}}"
                    title="Show Comments"><i class="fa fa-eye"></i></button>



            @can('isActive')
                <button type="button" class="btn btn-round  btn-primary"
                        @if(Auth::check())  onclick='openCommentModal("{{$post->id}}","{{htmlspecialchars_decode($post->title)}}")'
                        @else data-toggle="modal" data-target="#loginModal" @endif

                        title="Write Comment"><i class="fa fa-pencil"></i></button>
            @endcan

        </div>
    </div>
    <div id="comments{{$post->id}}" class="collapse p-1" style="max-height: 400px;overflow-y: auto">
        <h4 class="text-center">Comments</h4>
        @foreach($post->comments as $comment)
            @include('includes.comment')
        @endforeach
    </div>
</article>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->


    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    @yield('style')

    <style>


    </style>
</head>
<body>
<div id="app">
    <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
        <div class="container">
            <a class="navbar-brand" href="{{ url('/') }}">
                {{ config('app.name', 'Laravel') }}
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">

                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @endif
                    @else
                        @can('isAdmin')
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('posts.index') }}">Dashboard</a>
                            </li>
                        @endcan
                        <li class="nav-item dropdown">

                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                      style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
            </div>
        </div>
    </nav>

    <main class="py-4">
        @yield('content')
    </main>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jscroll/2.3.7/jquery.jscroll.min.js"></script>

@yield('script')
</body>
</html>

resources/views/modals/comment-modal.blade.php
<div class="modal" id="commentModal">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Comment for <span class="title" style="color: #3f9ae5"></span></h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <!-- Modal body -->
            <div class="modal-body">
                <form method="POST" id="commentStore">
                    <div class="form-group row  p-2">
                        <label for="text"><strong class="p-2">Text</strong></label>
                        <textarea class="form-control" id="text" rows="5" name="text" required
                                  maxlength="800"></textarea>
                    </div>
                    <input type="hidden" name="post_id" id="post_id">

                    <span class="invalid-feedback" role="alert" style="display: block">
                                        <strong id="error"></strong>
                            </span>

                    <div class="form-group row  p-2">
                        <div class="btn-group ml-auto">
                            <button type="button" class="btn btn-light" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

resources/views/modals/warning-modal.blade.php
<div class="modal" id="loginModal">
    <div class="modal-dialog">
        <div class="modal-content">

            <!-- Modal Header -->
            <div class="modal-header">
                <h4 class="modal-title">Place Login</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>

        </div>
    </div>
</div>